import type { ReadingModule } from '../schema';

export const STUDY_READINGS_D3: ReadingModule[] = [
  {
    id: 'fs-d3-geodesy',
    examTrack: 'fs',
    domainNumber: 3,
    domain: 'Applied Mathematics & Statistics',
    title: 'Geodesy Fundamentals',
    description: 'Understand the three reference surfaces used in surveying, the relationship between ellipsoidal and orthometric heights, geodetic datums in North America, and State Plane Coordinate System projections including scale factor conversions.',
    estimatedMinutes: 20,
    sections: [
      {
        id: 'fs-d3-geodesy-s1',
        type: 'concept',
        title: 'Three Reference Surfaces',
        content: 'Geodesy relies on three distinct reference surfaces to describe positions and elevations on and near the Earth.\n\nThe Ellipsoid is a mathematically defined smooth surface generated by rotating an ellipse about the Earth\'s polar axis. It approximates the overall shape of the Earth and serves as the reference for geodetic latitude, longitude, and ellipsoidal height. Different ellipsoids have been adopted historically (Clarke 1866 for NAD 27, GRS 80 for NAD 83). The ellipsoid is purely geometric and does not account for variations in gravity.\n\nThe Geoid is the equipotential surface of the Earth\'s gravity field that best fits mean sea level in a global least-squares sense. It is an irregular, undulating surface shaped by the uneven distribution of mass within the Earth. Water at rest (ignoring tides, currents, and weather) would closely conform to the geoid. Orthometric heights (traditional elevations referenced to mean sea level) are measured relative to the geoid.\n\nThe Topographic Surface is the actual physical surface of the Earth, including mountains, valleys, buildings, and vegetation. Survey measurements are collected on or near this surface. The topographic surface departs from both the ellipsoid and the geoid, sometimes by large amounts in mountainous regions.',
      },
      {
        id: 'fs-d3-geodesy-s2',
        type: 'concept',
        title: 'Geoid Undulation and Its Significance',
        content: 'Geoid undulation (also called geoid separation and symbolized by N) is the vertical distance between the ellipsoid and the geoid at any given location. Where the geoid lies above the ellipsoid, N is positive; where the geoid lies below, N is negative.\n\nAcross the conterminous United States, geoid undulation values typically range from about -8 meters to -53 meters, meaning the geoid generally sits below the GRS 80 ellipsoid used by NAD 83. The magnitude and sign of N vary with geographic location because the geoid reflects local mass distributions while the ellipsoid is a smooth mathematical shape.\n\nKnowing the geoid undulation is essential whenever GNSS-derived ellipsoidal heights must be converted to orthometric heights for engineering, mapping, or legal purposes. The National Geodetic Survey publishes geoid models (such as GEOID18) that provide interpolated N values across the country. Without applying the correct geoid undulation, a GNSS-measured height could differ from a leveled elevation by tens of meters.',
      },
      {
        id: 'fs-d3-geodesy-s3',
        type: 'formula',
        title: 'Ellipsoid-Geoid Height Relationship',
        formula: {
          expression: 'h = H + N',
          variables: [
            { symbol: 'h', description: 'Ellipsoidal height, the distance from the ellipsoid surface to the point measured along the ellipsoid normal (obtained from GNSS observations)' },
            { symbol: 'H', description: 'Orthometric height, the distance from the geoid to the point measured along the plumb line (traditional leveled elevation above mean sea level)' },
            { symbol: 'N', description: 'Geoid undulation (geoid separation), the distance from the ellipsoid to the geoid at that location (positive when the geoid is above the ellipsoid)' },
          ],
          whenToUse: 'Use this relationship whenever you need to convert between GNSS-derived ellipsoidal heights and traditional orthometric heights. Given any two of the three values, you can solve for the third. This is fundamental for combining GNSS data with leveling data in surveying projects.',
        },
      },
      {
        id: 'fs-d3-geodesy-s4',
        type: 'worked_example',
        title: 'Converting Between Orthometric and Ellipsoidal Heights',
        workedExample: {
          problem: 'A GNSS receiver at a benchmark records an ellipsoidal height of h = 245.83 m. The published geoid undulation at this location from the GEOID18 model is N = -32.45 m. Determine the orthometric height of the benchmark. Then, for a second point, if the orthometric height (leveled elevation) is H = 198.60 m and the geoid undulation is N = -29.10 m, compute the expected ellipsoidal height that a GNSS receiver would measure.',
          steps: [
            { step: 1, description: 'Write the height relationship formula.', calculation: 'h = H + N, therefore H = h - N' },
            { step: 2, description: 'Solve for orthometric height at the first point.', calculation: 'H = 245.83 - (-32.45) = 245.83 + 32.45 = 278.28 m' },
            { step: 3, description: 'For the second point, solve for ellipsoidal height.', calculation: 'h = H + N = 198.60 + (-29.10) = 169.50 m' },
          ],
          answer: 'The orthometric height at the first point is 278.28 m. The expected ellipsoidal height at the second point is 169.50 m. Note that because N is negative (geoid below ellipsoid) in these examples, the orthometric height is numerically larger than the ellipsoidal height.',
        },
      },
      {
        id: 'fs-d3-geodesy-s5',
        type: 'knowledge_check',
        title: 'Reference Surfaces Knowledge Check',
        knowledgeCheck: {
          question: 'Which reference surface is defined as the equipotential surface of the Earth\'s gravity field that most closely approximates mean sea level?',
          options: [
            'The ellipsoid',
            'The geoid',
            'The topographic surface',
            'The datum surface',
          ],
          correctIndex: 1,
          explanation: 'The geoid is the equipotential surface of the Earth\'s gravity field that best fits mean sea level globally. The ellipsoid is a smooth mathematical approximation of the Earth\'s shape and does not account for gravity variations. The topographic surface is the actual physical surface of the Earth. The term "datum surface" is not a standard reference surface in geodesy.',
        },
      },
      {
        id: 'fs-d3-geodesy-s6',
        type: 'concept',
        title: 'Geodetic Datums: NAD 27, NAD 83, NAVD 88, and WGS 84',
        content: 'A geodetic datum defines the size, shape, and orientation of the reference ellipsoid relative to the Earth, along with the origin and orientation of the coordinate system.\n\nNAD 27 (North American Datum of 1927) uses the Clarke 1866 ellipsoid and is a regional datum with its origin at Meigs Ranch in Kansas. All horizontal positions were derived from a network of triangulation observations adjusted to that single fixed origin. Because of its regional fit, NAD 27 coordinates can differ from modern values by tens of meters.\n\nNAD 83 (North American Datum of 1983) uses the GRS 80 ellipsoid, which is geocentric (its center coincides with the Earth\'s center of mass). NAD 83 incorporated satellite observations and replaced NAD 27 across the United States, Canada, and Mexico. Coordinates shifted by as much as 100 meters in some areas when transitioning from NAD 27 to NAD 83. NAD 83 has been refined through multiple adjustments, including high-accuracy reference networks (HARNs) and the multi-year CORS solution.\n\nNAVD 88 (North American Vertical Datum of 1988) is the current vertical datum for orthometric heights in the United States. It replaced NGVD 29 and is based on a minimum-constraint adjustment of leveling observations tied to a single primary benchmark (Father Point, Rimouski, Quebec). NAVD 88 heights can differ from NGVD 29 heights by up to about 1.5 meters in parts of the western United States.\n\nWGS 84 (World Geodetic System 1984) is the global datum used by the GPS satellite constellation. Its ellipsoid is nearly identical to GRS 80 (differing only in the flattening parameter by a negligible amount). For practical survey purposes, WGS 84 and NAD 83 coordinates are compatible at the sub-meter level, though at centimeter accuracy they diverge due to tectonic motion and different realization epochs.',
      },
      {
        id: 'fs-d3-geodesy-s7',
        type: 'concept',
        title: 'State Plane Coordinate Systems',
        content: 'State Plane Coordinate Systems (SPCS) project geodetic coordinates (latitude and longitude) onto a flat plane so that surveyors can work in a Cartesian coordinate system with minimal distortion. Each state is divided into one or more zones to keep scale distortion within acceptable limits (typically less than 1 part in 10,000).\n\nTwo conformal map projections are used:\n\nLambert Conformal Conic projection is used for zones that extend farther in the east-west direction than in the north-south direction. Two standard parallels are selected where the projection cone intersects the ellipsoid. Scale is exact along these parallels, slightly compressed between them, and slightly expanded outside them.\n\nTransverse Mercator projection is used for zones that extend farther in the north-south direction. A central meridian is selected where the projection cylinder is tangent (or secant) to the ellipsoid. Scale is exact along lines parallel to and equidistant from the central meridian (in the secant case), slightly compressed along the central meridian itself, and increases with distance east or west of the central meridian.\n\nThe choice between Lambert and Transverse Mercator depends solely on the shape of the zone. Wide zones use Lambert; tall, narrow zones use Transverse Mercator. A few states (such as Alaska) also use an Oblique Mercator projection for panhandle-shaped zones.\n\nSPCS coordinates are typically expressed in US survey feet or meters, depending on state legislation. When working in SPCS, surveyors must apply scale factors to convert between ground distances and grid distances.',
      },
      {
        id: 'fs-d3-geodesy-s8',
        type: 'formula',
        title: 'Grid Distance and Combined Scale Factor',
        formula: {
          expression: 'Grid Distance = Ground Distance * k; Combined Factor (CF) = Elevation Factor * Grid Scale Factor',
          variables: [
            { symbol: 'Grid Distance', description: 'The distance as computed on the State Plane Coordinate System grid' },
            { symbol: 'Ground Distance', description: 'The horizontal distance measured on the Earth\'s surface at the project elevation' },
            { symbol: 'k', description: 'The combined scale factor that converts ground distance to grid distance' },
            { symbol: 'Elevation Factor', description: 'The ratio R / (R + H_avg) where R is the mean radius of the Earth (approximately 20,906,000 ft or 6,372,000 m) and H_avg is the average orthometric height of the line above the ellipsoid' },
            { symbol: 'Grid Scale Factor', description: 'The scale factor at a point on the SPCS projection, obtained from projection tables, software, or NGS tools; it accounts for the distortion introduced by projecting the curved ellipsoid onto a flat plane' },
          ],
          whenToUse: 'Apply the combined factor whenever converting field-measured ground distances to State Plane grid distances or vice versa. The elevation factor reduces the ground distance to the ellipsoid surface, and the grid scale factor then maps the ellipsoidal distance onto the projection plane. Multiply these two factors to get the combined factor.',
        },
      },
      {
        id: 'fs-d3-geodesy-s9',
        type: 'worked_example',
        title: 'Applying the Combined Scale Factor',
        workedExample: {
          problem: 'A surveyor measures a ground distance of 2,500.00 ft between two points on a project site. The average orthometric elevation of the line is 1,200 ft above the ellipsoid. The grid scale factor at the midpoint of the line from the State Plane projection is 0.99996500. Using a mean Earth radius of 20,906,000 ft, compute the combined factor and the grid distance.',
          steps: [
            { step: 1, description: 'Compute the elevation factor.', calculation: 'Elevation Factor = R / (R + H_avg) = 20,906,000 / (20,906,000 + 1,200) = 20,906,000 / 20,907,200 = 0.99994262' },
            { step: 2, description: 'Compute the combined factor by multiplying the elevation factor by the grid scale factor.', calculation: 'Combined Factor = 0.99994262 * 0.99996500 = 0.99990762' },
            { step: 3, description: 'Convert the ground distance to grid distance.', calculation: 'Grid Distance = 2,500.00 * 0.99990762 = 2,499.77 ft' },
          ],
          answer: 'The combined factor is 0.99990762 and the grid distance is 2,499.77 ft. The grid distance is slightly shorter than the ground distance because both the elevation reduction and the grid scale factor are less than 1.0 in this example.',
        },
      },
      {
        id: 'fs-d3-geodesy-s10',
        type: 'knowledge_check',
        title: 'Datums and Projections Knowledge Check',
        knowledgeCheck: {
          question: 'A State Plane zone that is significantly wider (east to west) than it is tall (north to south) would most likely use which map projection?',
          options: [
            'Transverse Mercator',
            'Lambert Conformal Conic',
            'Oblique Mercator',
            'Polyconic',
          ],
          correctIndex: 1,
          explanation: 'Lambert Conformal Conic is the standard projection for State Plane zones that extend primarily in the east-west direction. The two standard parallels of the conic projection minimize distortion across the width of such zones. Transverse Mercator is chosen for zones that are elongated in the north-south direction. Oblique Mercator is used only in special cases such as the Alaska panhandle. Polyconic is not used in the State Plane Coordinate System.',
        },
      },
      {
        id: 'fs-d3-geodesy-s11',
        type: 'further_reading',
        title: 'Further Reading',
        furtherReading: [
          { book: 'Elementary Surveying, 15th Edition', chapter: 'Chapter 19', topic: 'Control Surveys and Geodetic Reductions' },
          { book: 'Surveyor Reference Manual', chapter: 'Chapter 7', topic: 'Geodesy and Survey Astronomy' },
          { book: 'NOAA National Geodetic Survey', chapter: 'Online Resources', topic: 'Geoid Models, CORS Network, and State Plane Coordinate Definitions' },
        ],
      },
    ],
  },
  {
    id: 'fs-d3-gnss',
    examTrack: 'fs',
    domainNumber: 3,
    domain: 'Applied Mathematics & Statistics',
    title: 'GNSS & Satellite Surveying',
    description: 'Learn how Global Navigation Satellite Systems work, including GPS and other constellations, error sources that affect positioning accuracy, dilution of precision concepts, and field methods such as static, RTK, and CORS/OPUS processing.',
    estimatedMinutes: 18,
    sections: [
      {
        id: 'fs-d3-gnss-s1',
        type: 'concept',
        title: 'GNSS Overview and Positioning Principles',
        content: 'Global Navigation Satellite Systems (GNSS) is the umbrella term for all satellite-based positioning constellations. The four major constellations are:\n\nGPS (Global Positioning System) operated by the United States with a nominal constellation of 31 satellites in six orbital planes at approximately 20,200 km altitude. GPS was the first fully operational satellite navigation system and remains the most widely used.\n\nGLONASS (Globalnaya Navigatsionnaya Sputnikovaya Sistema) operated by Russia with 24 satellites in three orbital planes at approximately 19,100 km altitude. GLONASS uses frequency-division multiple access (FDMA) signals, though newer satellites also transmit code-division multiple access (CDMA) signals.\n\nGalileo is operated by the European Union with a planned 30-satellite constellation (including spares) in three orbital planes at approximately 23,222 km altitude. Galileo provides civilian-controlled positioning and is designed for interoperability with GPS.\n\nBeiDou (BDS) is operated by China with a constellation that includes satellites in medium Earth orbit, geostationary orbit, and inclined geosynchronous orbit, providing global coverage.\n\nAll GNSS systems operate on the same fundamental principle of trilateration. Each satellite continuously broadcasts its precise position (ephemeris) and the exact time of transmission. A receiver measures the signal travel time from each satellite and multiplies by the speed of light to obtain a pseudorange. With pseudoranges from at least four satellites, the receiver can solve for three unknown position coordinates (X, Y, Z) and the receiver clock error. Using satellites from multiple constellations improves availability, geometry, and reliability.',
      },
      {
        id: 'fs-d3-gnss-s2',
        type: 'concept',
        title: 'GNSS Error Sources',
        content: 'Multiple error sources affect GNSS positioning accuracy. Understanding them is critical for selecting appropriate survey methods and achieving required precisions.\n\nIonospheric Delay: The ionosphere (approximately 50 to 1,000 km above the Earth) contains free electrons that slow the GNSS code signal and advance the carrier phase. This delay can introduce errors of 2 to 50 meters in single-frequency pseudoranges. Dual-frequency receivers can model and largely eliminate ionospheric delay because the effect is frequency-dependent.\n\nTropospheric Delay: The lower atmosphere (troposphere, up to about 40 km) causes signal delays due to temperature, pressure, and humidity variations. Unlike the ionosphere, tropospheric delay is not frequency-dependent and cannot be removed by dual-frequency techniques. It is modeled using atmospheric parameters and mapping functions.\n\nMultipath: GNSS signals can reflect off nearby surfaces (buildings, vehicles, water, terrain) before reaching the antenna, causing the receiver to measure a longer-than-actual path. Multipath errors range from centimeters to meters. They are mitigated by careful antenna placement, ground planes, choke ring antennas, and extended observation times.\n\nSatellite Clock and Orbit Errors: Although satellite clocks are atomic, small clock drift occurs. Broadcast ephemerides contain orbital predictions that also have errors. These are reduced by differential correction, precise ephemerides, and real-time correction services.\n\nReceiver Clock Error: Consumer-grade quartz oscillators in receivers are far less stable than satellite atomic clocks. The receiver clock bias is solved as a fourth unknown in the position solution, which is why a minimum of four satellites is required.\n\nPDOP and GDOP: Dilution of Precision (DOP) quantifies how satellite geometry affects position accuracy. When satellites are clustered together in one part of the sky, the geometry is weak and DOP values are high. When satellites are spread across the sky, geometry is strong and DOP is low. PDOP (Position DOP) relates to 3D position, HDOP to horizontal, VDOP to vertical, and GDOP (Geometric DOP) includes the time component. A PDOP below 4 is generally considered acceptable for survey work; below 2 is excellent.',
      },
      {
        id: 'fs-d3-gnss-s3',
        type: 'formula',
        title: 'Dilution of Precision (DOP) Concept',
        formula: {
          expression: 'PDOP = sqrt(sigma_x^2 + sigma_y^2 + sigma_z^2) / sigma_range',
          variables: [
            { symbol: 'PDOP', description: 'Position Dilution of Precision, a unitless factor that multiplies the ranging error to give 3D position error' },
            { symbol: 'sigma_x', description: 'Standard deviation of the position estimate in the X-direction resulting from satellite geometry' },
            { symbol: 'sigma_y', description: 'Standard deviation of the position estimate in the Y-direction resulting from satellite geometry' },
            { symbol: 'sigma_z', description: 'Standard deviation of the position estimate in the Z-direction resulting from satellite geometry' },
            { symbol: 'sigma_range', description: 'Standard deviation of a single pseudorange measurement (User Equivalent Range Error)' },
          ],
          whenToUse: 'Use DOP values to evaluate whether the current satellite geometry will support the required survey accuracy. A lower PDOP indicates better geometry and more precise positioning. As a rule of thumb, PDOP below 2 is excellent, 2 to 4 is good, 4 to 6 is acceptable for lower-accuracy work, and above 6 should be avoided for survey-grade observations. Always check PDOP before beginning GNSS observations in the field.',
        },
      },
      {
        id: 'fs-d3-gnss-s4',
        type: 'worked_example',
        title: 'Interpreting DOP Values for Survey Quality',
        workedExample: {
          problem: 'A surveyor is planning a GNSS observation session. Mission planning software shows two available observation windows:\n\nWindow A (10:00-11:00): 8 satellites visible, PDOP = 1.8, HDOP = 1.0, VDOP = 1.5\nWindow B (14:00-15:00): 6 satellites visible, PDOP = 4.9, HDOP = 2.8, VDOP = 4.1\n\nThe project specification requires horizontal accuracy of 2 cm and vertical accuracy of 3 cm. The receiver manufacturer states the expected User Equivalent Range Error (UERE) is 1.5 cm in carrier-phase mode. Determine which window is suitable and estimate the expected position errors.',
          steps: [
            { step: 1, description: 'Estimate horizontal position error for Window A.', calculation: 'Horizontal error = HDOP * UERE = 1.0 * 1.5 cm = 1.5 cm' },
            { step: 2, description: 'Estimate vertical position error for Window A.', calculation: 'Vertical error = VDOP * UERE = 1.5 * 1.5 cm = 2.25 cm' },
            { step: 3, description: 'Compare Window A results to specifications.', calculation: 'Horizontal: 1.5 cm < 2 cm requirement (PASS). Vertical: 2.25 cm < 3 cm requirement (PASS).' },
            { step: 4, description: 'Estimate horizontal position error for Window B.', calculation: 'Horizontal error = HDOP * UERE = 2.8 * 1.5 cm = 4.2 cm' },
            { step: 5, description: 'Estimate vertical position error for Window B.', calculation: 'Vertical error = VDOP * UERE = 4.1 * 1.5 cm = 6.15 cm' },
            { step: 6, description: 'Compare Window B results to specifications.', calculation: 'Horizontal: 4.2 cm > 2 cm requirement (FAIL). Vertical: 6.15 cm > 3 cm requirement (FAIL).' },
          ],
          answer: 'Window A is the suitable observation window. With PDOP = 1.8, the expected horizontal error is 1.5 cm and vertical error is 2.25 cm, both within specifications. Window B with PDOP = 4.9 yields estimated errors of 4.2 cm horizontal and 6.15 cm vertical, which exceed the project requirements. The higher DOP values in Window B indicate poor satellite geometry, likely because the six visible satellites are clustered in a limited portion of the sky.',
        },
      },
      {
        id: 'fs-d3-gnss-s5',
        type: 'knowledge_check',
        title: 'GNSS Errors Knowledge Check',
        knowledgeCheck: {
          question: 'Which GNSS error source can be largely eliminated by using a dual-frequency receiver?',
          options: [
            'Tropospheric delay',
            'Multipath',
            'Ionospheric delay',
            'Receiver antenna phase center variation',
          ],
          correctIndex: 2,
          explanation: 'Ionospheric delay is frequency-dependent, meaning dual-frequency receivers can measure the difference in delay between two frequencies and mathematically remove the ionospheric effect. Tropospheric delay is not frequency-dependent and must be modeled using atmospheric parameters. Multipath is caused by signal reflections from nearby surfaces and is mitigated by antenna design and site selection, not by dual-frequency observations. Antenna phase center variation is addressed through calibration models, not frequency diversity.',
        },
      },
      {
        id: 'fs-d3-gnss-s6',
        type: 'concept',
        title: 'GNSS Survey Methods',
        content: 'Several GNSS field methods exist, each suited to different accuracy requirements and project conditions.\n\nStatic Surveying involves placing receivers on two or more points simultaneously and collecting data for extended periods (typically 30 minutes to several hours depending on baseline length). Post-processing software resolves integer carrier-phase ambiguities using the accumulated data. Static surveying achieves the highest accuracy (sub-centimeter over baselines up to hundreds of kilometers) and is the standard for establishing geodetic control networks.\n\nRapid Static is a shorter-occupation variant of static surveying. Observation times range from about 5 to 20 minutes per point, depending on satellite availability, baseline length, and the number of frequencies observed. Accuracy is slightly lower than full static but still at the centimeter level. Rapid static is efficient for densifying control networks where many points must be occupied in one day.\n\nReal-Time Kinematic (RTK) uses a base station on a known point that transmits real-time corrections (via radio or cellular modem) to a rover receiver. The rover resolves ambiguities in real time and can achieve centimeter-level horizontal accuracy and 2-3 cm vertical accuracy as the surveyor moves from point to point. RTK is efficient for topographic surveys, stakeout, and boundary surveys but is limited by the baseline distance to the base (typically under 10-20 km) and requires a reliable communications link.\n\nPost-Processed Kinematic (PPK) collects data in the same manner as RTK but without real-time corrections. Instead, base and rover data are combined in post-processing software after returning from the field. PPK is useful in areas with poor radio or cellular coverage and achieves similar accuracy to RTK.\n\nCORS and OPUS: Continuously Operating Reference Stations (CORS) are permanent GNSS base stations operated by government agencies and private networks. The NGS Online Positioning User Service (OPUS) allows surveyors to upload static observation files and receive processed coordinates referenced to the National Spatial Reference System. OPUS eliminates the need to set up a local base station and provides results tied to multiple CORS stations for quality assurance.',
      },
      {
        id: 'fs-d3-gnss-s7',
        type: 'concept',
        title: 'RTK vs. Static: Choosing the Right Method',
        content: 'Selecting between RTK and static GNSS surveying depends on the accuracy requirement, project type, baseline length, and field conditions.\n\nUse Static Surveying when:\n- Establishing primary or secondary geodetic control networks\n- Baseline lengths exceed 20 km\n- The highest possible accuracy is required (sub-centimeter)\n- Reliable real-time communication is not available\n- Project specifications mandate static observations (e.g., NGS Bluebooking)\n\nExpected accuracy: 5 mm + 0.5 ppm horizontal, 10 mm + 0.5 ppm vertical (typical for 1-hour observations with dual-frequency receivers).\n\nUse RTK Surveying when:\n- Performing topographic surveys, boundary surveys, or construction stakeout\n- Real-time positions are needed in the field for immediate decisions\n- Baselines to the base station (or RTK network) are under 10-20 km\n- Centimeter-level accuracy is sufficient\n- Many points must be surveyed quickly (seconds per point vs. minutes or hours)\n\nExpected accuracy: 10-20 mm horizontal, 20-30 mm vertical (varies with baseline length and conditions).\n\nIn practice, many projects combine both methods. Static observations establish control points, and RTK is then used for detail surveying referenced to those control points. This hybrid approach provides high accuracy where needed and efficiency for production surveying.',
      },
      {
        id: 'fs-d3-gnss-s8',
        type: 'knowledge_check',
        title: 'GNSS Methods Knowledge Check',
        knowledgeCheck: {
          question: 'A surveyor needs to establish a high-accuracy geodetic control point with a 75 km baseline to the nearest known control. Which GNSS method is most appropriate?',
          options: [
            'Real-Time Kinematic (RTK)',
            'Rapid static with 5-minute occupations',
            'Static surveying with extended observation time',
            'Single-point autonomous positioning',
          ],
          correctIndex: 2,
          explanation: 'For a 75 km baseline requiring high accuracy, static surveying with extended observation time (typically 2+ hours for baselines of this length) is the correct choice. RTK is impractical at 75 km because it typically operates within 10-20 km of the base station and its accuracy degrades significantly over long baselines. Rapid static observations of only 5 minutes would not collect enough data to reliably resolve carrier-phase ambiguities over such a long baseline. Single-point autonomous positioning provides only meter-level accuracy and is unsuitable for geodetic control work.',
        },
      },
      {
        id: 'fs-d3-gnss-s9',
        type: 'further_reading',
        title: 'Further Reading',
        furtherReading: [
          { book: 'Elementary Surveying, 15th Edition', chapter: 'Chapters 13-14', topic: 'Global Navigation Satellite Systems and Satellite Positioning' },
          { book: 'Surveyor Reference Manual', chapter: 'Chapter 7 (GPS Section)', topic: 'GPS Surveying Methods and Error Analysis' },
        ],
      },
    ],
  },
];
